services:
  mongodb:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:8080"
    env_file:
      - ./backend/.env.sample
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.sample
    depends_on:
      - backend

volumes:
  data:
